#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-present Team LibreELEC (https://libreelec.tv)

# Derive the kodi addon branch from the repo's OS_VERSION
OS_VERSION=$(grep 'OS_VERSION=' distributions/LibreELEC/version | tr -d ' "' | cut -d'=' -f2)

case "$OS_VERSION" in
  13.0)
    ADDON_BRANCH="master"
    ;;
  12.2)
    ADDON_BRANCH="Omega"
    ;;
  12.0)
    ADDON_BRANCH="Omega"
    ;;
  *)
    echo "ERROR: Unknown OS_VERSION '$OS_VERSION' - add a case for it"
    exit 1
    ;;
esac

echo "Running for OS_VERSION=$OS_VERSION  addon_branch=$ADDON_BRANCH"

PROJECT=Generic ARCH=x86_64 DEVICE=Generic-legacy \
  tools/mkpkg/update_binary-addons --commit -x "$ADDON_BRANCH"
