#!/bin/sh
################################################################################
#      This file is part of LibreELEC - https://libreelec.tv
#      Copyright (C) 2018-present Team LibreELEC
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

PACKAGE_NAME="nfs-ganesha"

echo "getting sources..."
  if [ ! -d $PACKAGE_NAME.git ]; then
    git clone --depth=1 -b V2.6-stable --recurse-submodules https://github.com/nfs-ganesha/nfs-ganesha.git $PACKAGE_NAME.git
  fi

  cd $PACKAGE_NAME.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf $PACKAGE_NAME-$GIT_REV
  cp -R $PACKAGE_NAME.git/src $PACKAGE_NAME-$GIT_REV

echo "cleaning sources..."
  rm -rf $PACKAGE_NAME-$GIT_REV/.git

echo "packing sources..."
  tar cvJf $PACKAGE_NAME-$GIT_REV.tar.xz $PACKAGE_NAME-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf $PACKAGE_NAME-$GIT_REV
